on: push
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: 'checkout'
        uses: actions/checkout@v3.0.0
      - name: 'build and deploy'
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          PAGES_BRANCH: main
          BUILD_DIR: ./public
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

